import { pool } from "./db";

// Auto-applies the Online Listening legitimacy backfill on app start.
//
// Two passes against `online_listening_mentions`:
//   1. Tag every legacy row (no `metadata.provenance`) as
//      `is_verified = false` and add `provenance='unknown'`,
//      `legacy=true`, `metricsAreReal=false` to metadata.
//   2. Scrub `source_url` for X/Twitter URLs whose status ID is < 15
//      digits (real X status IDs are 15–20 digits; anything shorter
//      was generated by the old hashAbs-based chi-demo seeder).
//
// Idempotent: the WHERE clauses filter out already-tagged or already-scrubbed
// rows, so this is safe to run on every app start.
//
// Source of truth: migrations/0011_online_listening_legitimacy_backfill.sql.
// If you edit either copy, update both. The .sql file is the auditable
// artifact for ops and manual application; this file makes the migration
// auto-run in every environment without operator action.
const BACKFILL_SQL = `
BEGIN;

UPDATE online_listening_mentions
SET
  is_verified = false,
  metadata = COALESCE(metadata, '{}'::jsonb) || jsonb_build_object(
    'provenance', 'unknown',
    'legacy', true,
    'metricsAreReal', false
  )
WHERE metadata->>'provenance' IS NULL;

UPDATE online_listening_mentions
SET source_url = NULL
WHERE metadata->>'provenance' = 'unknown'
  AND source_url IS NOT NULL
  AND source_url ~ '^https?://(twitter|x)\\.com/[^/]+/status/[0-9]{1,14}$';

COMMIT;
`;

export async function runOnlineListeningBackfill(): Promise<void> {
  const start = Date.now();
  const result = await pool.query(BACKFILL_SQL);
  const ms = Date.now() - start;

  // pg returns an array of result objects when multi-statement SQL is run;
  // the two UPDATE statements report rowCount independently. Surface both
  // so operators can see at a glance whether legacy rows existed.
  const rowCounts = Array.isArray(result)
    ? result.map((r: any) => r.rowCount ?? 0)
    : [(result as any).rowCount ?? 0];
  const taggedAsLegacy = rowCounts[1] ?? 0;
  const urlsScrubbed = rowCounts[2] ?? 0;

  console.log(
    `[OnlineListeningBackfill] applied in ${ms}ms (legacy_rows_tagged=${taggedAsLegacy}, fake_x_urls_scrubbed=${urlsScrubbed})`
  );
}
